### ISSUE TITLE
sg_get_process_count() returning a higher count on some Oracle Linux boxes running kernel UEK

### ISSUE THREAD

**Issue by andersontrindade0975** [libstatgrab/libstatgrab#122]
Linux version: Oracle Linux Server release 7.8
kernel version: 4.14.35-1902.302.2.el7uek.x86_64

Issue:
libstatgrab is reporting a number of "running" process a lot higher, comparing to the number of process reported by vmstat as we can see from the output below:

$ statgrab | grep proc.running; vmstat
proc.running = 361
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
18  0      0 333290112  59240 26311372    0    0  1432   422    0    0 31  1 68  0  0

Still trying to get more detail but, the problem is being reproduced on some different Oracle Linux installations:

Kernel Version                                  Linux version
---------------------------------- -------------------------------
4.14.35-1902.302.2.el7uek.x86_64 Oracle Linux Server release 7.8
4.14.35-1844.2.5.el7uek.x86_64	Oracle Linux Server release 7.6
4.1.12-112.16.8.el6uek.x86_64	Oracle Linux Server release 6.9
4.1.12-112.16.8.el6uek.x86_64	Oracle Linux Server release 6.9
4.1.12-112.16.8.el6uek.x86_64	Oracle Linux Server release 6.9
4.1.12-112.16.8.el6uek.x86_64	Oracle Linux Server release 6.9
4.14.35-1902.11.3.1.el7uek.x86_64 Oracle Linux Server release 7.7
4.1.12-124.20.3.el6uek.x86_64	Oracle Linux Server release 6.10
4.1.12-124.20.3.el6uek.x86_64	Oracle Linux Server release 6.10
4.1.12-124.18.6.el6uek.x86_64	Oracle Linux Server release 6.10
4.1.12-124.18.6.el6uek.x86_64	Oracle Linux Server release 6.10
4.1.12-124.30.1.el6uek.x86_64	Oracle Linux Server release 6.10
4.1.12-124.30.1.el6uek.x86_64	Oracle Linux Server release 6.10

**Comment by tdb** [comment]
I can confirm this issue. It's idle processes (state `I`) being counted as running by mistake. We'll sort out a fix.

**Comment by tdb** [comment]
#123 is a minimal fix. It classifies these processes as unknown (rather than mistakenly as running). A fuller fix would be to add an additional process state of idle. But this is enough to ensure `running` is correct.

**Comment by tdb** [comment]
@andersontrindade0975 This has been fixed in master and will be in the next release. If you want to test it out you can download this tarball which contains the latest code:

https://gitlab.com/libstatgrab/libstatgrab/-/jobs/720961424/artifacts/raw/libstatgrab-a36df007.tar.gz

Here's an example of the difference in output:

```
[/tmp/libstatgrab-a36df007/src/statgrab] % /usr/bin/statgrab proc. ; echo ; ./statgrab proc.
proc.running = 417
proc.sleeping = 759
proc.stopped = 3
proc.total = 1179
proc.zombie = 0

proc.running = 26
proc.sleeping = 766
proc.stopped = 3
proc.total = 1186
proc.zombie = 0
[/tmp/libstatgrab-a36df007/src/statgrab] %
```

Previous output is first, new version is second. There is some difference caused by other activity on the machine, but the running figure is significantly different.

**Comment by andersontrindade0975** [comment]
@tdb, I've tested and it's working as expected now.
Thanks
