### ISSUE TITLE
libstatgrab returning failed to parse input (not all from 'cpu', 'intr', 'ctxt', 'softirq' found in '/proc/stat') on very older Linux kernels

### ISSUE THREAD

**Issue by andersontrindade0975** [libstatgrab/libstatgrab#124]
Scenario:
libstatgrab, version 0.92
Linux: Red Hat Enterprise Linux Server release 5.8 (Tikanga)
kernel: 2.6.18-308.el5 

sample from  /proc/stat:

cpu  18586839 2778 1352412 1042991263 13325089 233546 1339797 0
cpu0 2004901 6 94998 266665069 689946 0 3026 0
cpu1 7457682 1608 586971 254413646 6337841 111160 549022 0
cpu2 4501376 485 347268 260712591 3439678 66105 390420 0
cpu3 4622878 677 323174 261199956 2857623 56280 397327 0
intr 3816107288 2694989123 0 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 63 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 548560172 0 0 0 0 0 0 0 116023946 0 0 0 0 0 0 0 125125056 0 0 0 0 0 0 0 114902213 0 0 0 0 0 0 0 123535670 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 90339499 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2631542 0 0 0 0 0
ctxt 1217111454
btime 1598202327
processes 3810640
procs_running 1
procs_blocked 0

Issue:

sg_get_cpu_stats_int() seens to find at least four lines of interest on /proc/stats. Each of then, starting with: cpu, intr, ctxt and softirq. However, this LInux version is not including softirq data on /proc/stats

**Comment by tdb** [comment]
@andersontrindade0975 as a workaround you can just comment/remove this line:

https://github.com/libstatgrab/libstatgrab/blob/master/src/libstatgrab/cpu_stats.c#L264

We'll consider whether this test is necessary or not.

**Comment by andersontrindade0975** [comment]
Thanks @tdb , I will apply the suggested workaround.

**Comment by tdb** [comment]
Fixed by #125.
