### ISSUE TITLE
Autoconf 2.71 FTBFS

### ISSUE THREAD

**Issue by ofalk** [libstatgrab/libstatgrab#129]
Hi!

Given
    https://bugzilla.redhat.com/show_bug.cgi?id=1943112

I'd like to raise this upstream issue. Seems there was anyway no release up libstatgrab in a while.

Thanks,
 Oliver

**Comment by tdb** [comment]
Build failure log example: https://download.copr.fedorainfracloud.org/results/odubaj/autoconf-2.70/fedora-rawhide-x86_64/02095569-libstatgrab/builder-live.log.gz

This has already been fixed via #128, but hasn't yet been released.

**Comment by ofalk** [comment]
Any chance a new release will be assembled any time soon? Given there was none since 2019, I guess it could be anyway a good idea, right?

**Comment by rehsack** [comment]
I want to fix FBSD12 vmmeter issue before ... thank to new laptop I can install appropriate VM soon.

**Comment by ofalk** [comment]
Thx a lot! Looking forward to it!

**Comment by moto-timo** [comment]
Can we get an update? Any chance you can test this @rehsack ?

**Comment by rehsack** [comment]
@moto-timo: I forgot my SSD with the FreeBSD VM at my 2nd location - getting it back tomorrow. Please remind me 16:00 UTC when you didn't receive vmmeter before.

**Comment by moto-timo** [comment]
With Fedora 35 rebuild around the corner, we need a release please. @tdb @rehsack

**Comment by tdb** [comment]
@moto-timo @ofalk can you check the new release does what you need? https://github.com/libstatgrab/libstatgrab/releases/tag/LIBSTATGRAB_0_92_1

**Comment by moto-timo** [comment]
@tdb Thank you for the release. We're all in this together!

**Comment by ofalk** [comment]
I'm late to the party. Thanks @tdb for the release! I see it's already in F35.
