### ISSUE TITLE
Warning when building statgrab on photon OS 3.0 (usage of deprecated readdir_r)

### ISSUE THREAD

**Issue by jamesiotech** [libstatgrab/libstatgrab#134]
Building statgrab on photon linux  generated the warnings shown below. 

process_stats.c: In function 'scan_proc_dir':
process_stats.c:226:2: warning: 'readdir_r' is deprecated [-Wdeprecated-declarations]
  while( ( rc = readdir_r( proc_dir, dir_entry, &result ) ) == 0 ) {
  ^~~~~
In file included from tools.h:145:0,
                 from process_stats.c:26:
/usr/include/dirent.h:183:12: note: declared here
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~

**Comment by rehsack** [comment]
Duplicate of https://github.com/libstatgrab/libstatgrab/issues/101
