### ISSUE TITLE
ModuleNotFoundError: No module named 'statgrab'

### ISSUE THREAD

**Issue by shaheena86** [libstatgrab/libstatgrab#136]
I am on Debian11.3 with Python3.9
While I am importing the statgrab module I get the error module not found.

Everything worked fine when I was on Debian10 with Python3.7

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
root@shaheena-build:/tmp/libstatgrab-0.92.1# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import statgrab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'statgrab'
>>>
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

What can be done to fix this ?

**Comment by tdb** [comment]
You'll need to install the pystatgrab python module. Have you done that?

https://libstatgrab.org/pystatgrab/

**Comment by shaheena86** [comment]
No, I had not. 
I installed pystatgrab module and now it works fine.
Thanks :)
