### ISSUE TITLE
Is library still supported

### ISSUE THREAD

**Issue by rodgreennc** [libstatgrab/libstatgrab#137]
There hasn't been a new release in 2 years, and the last issue was a year ago.  Is the library still actively supported?

**Comment by tdb** [comment]
Well, I'm still seeing issues. What's your definition of actively supported? Nobody is paid for this, but we'll do our best if issues come up.

**Comment by rodgreennc** [comment]
Since there hasn't been a release in 2 years, my company is concerned that the library might have been, as they phrase it, "abandoned".  I think a primary concern is that if there were to be a security vulnerability identified, that there would be developers looking at it.
My own perception is that the library is pretty much mature, and doesn't require active changes. 
Thank you for confirming that a new issue is being accepted and given attention.

**Comment by tdb** [comment]
My employer has the same concerns about various software packages too, so I understand where you're coming from.

If there was a security issue then I would definitely do my best to resolve it, especially if fixes were provided.

And yes, it does seem to have gotten to a mature point. It'd just be fixes for new OS versions I guess.

**Comment by rodgreennc** [comment]
Thanks Tim
