### ISSUE TITLE
Bug: libstatgrab vm-stats example shows weird usage percentage

### ISSUE THREAD

**Issue by aholster** [libstatgrab/libstatgrab#138]
I am not sure if this repo is still maintained.
The vm-stats example seems to calculate a really odd 'total VM usage' 
![image](https://github.com/libstatgrab/libstatgrab/assets/47298483/92dcc8e9-837c-48e0-9626-0f47cd3fcaf8)
as you can see from the numbers, it is reporting a usage rate of upwards of 98% when the real number should be closer to 50%

The usage of the term 'VM' is also odd as the functions used are documented as talking about 'real' memory.

To reproduce, simply run the vm-stats executable after compiling it.

**Comment by tdb** [comment]
The line of code is here:

https://github.com/libstatgrab/libstatgrab/blob/master/examples/vm_stats.c#L78

Looks like it was written 20 years ago (!), and that calculation doesn't look right to me. It is just done in the example though, so it's a case of a poor example rather than the library code itself doing something wrong.

**Comment by aholster** [comment]
ah, that's good to know, thank you for the quick reaction!

**Comment by tdb** [comment]
Just messing around with the example and this change looks like it might do the right thing:

```diff
--- a/examples/vm_stats.c
+++ b/examples/vm_stats.c
@@ -75,7 +75,7 @@ int main(int argc, char **argv){
                total = mem_stats->total + swap_stats->total;
                free = mem_stats->free + swap_stats->free;

-               printf("Total VM usage : %5.2f%%\n", 100 - (((float)total/(float)free)));
+               printf("Total VM usage : %5.2f%%\n", 100 - (100*((float)free/(float)total)));
        }
        else {
                sg_die("Unable to get VM stats", 1);
```

**Comment by aholster** [comment]
i've added that into my local example too and that fixes the issue perfectly
